Feature/exercícios
v1cferr/orion-bootcamp pull request #1
Opened 2023-10-10 00:06 UTC by victor-ferreira-dev

2023-10-10 00:34 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Victor Ferreira] Exercício-1](https://trello.com/c/BkLBVpzV/40-victor-ferreira-exerc%C3%ADcio-1)

2023-10-11 01:08 UTC, danielsaviosec requested changes

2023-10-11 01:08 UTC, danielsaviosec commented on src/exercícios/1-um/script.ts
> +let palavraEscolhida: string = "antedeguemon";
palavra escolhida pode ser uma const, ja que é um valor inalterável.

2023-10-11 01:08 UTC, danielsaviosec commented on src/exercícios/1-um/script.ts
> +                palavra[i] == "a" ||
A não ser que aceite a comparação entre tipos diferentes de dados aqui, é legal utilizar o operador de equivalência total (===).

2023-10-11 01:08 UTC, danielsaviosec commented on src/exercícios/1-um/script.ts
> +        let quantidade = 0;
tipar as variáveis de dentro da função

2023-10-13 03:33 UTC, victor-ferreira-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Victor Ferreira] Exercício-2](https://trello.com/c/ZgqW5VMr/49-victor-ferreira-exerc%C3%ADcio-2)

2023-10-13 21:37 UTC, danielsaviosec requested changes
Os arquivos do exercício 2 ainda estão no PR do exercício 1

2023-10-14 00:40 UTC, closed without merging